### ISSUE TITLE
PHP 7.4 notices that cause errors in XHR

### ISSUE THREAD

**Issue by ronaldtveen** [stripe-samples/web-elements-ideal-payment#7]
# Bug report

## Describe the bug

When running the example in PHP 7.4 I'm getting a couple notices in the PHP output that is causing the ajax request to error out (expected JSON, got mix of JSON+HTML with the notice). Even though I can disable the error reporting, I think it's better to actually fix them.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. I run the server
2. I navigate to `http://127.0.0.1:4242/`
3. I click the iDEAL tab
4. I pick a random bank from the dropdown list followed by the green [PAY] button
5. I'm navigated to the stripe.com iDEAL test payment page where I click the purple [AUTHORIZE TEST PAYMENT] button
6. I'm navigated back to `http://127.0.0.1:4242/complete?payment_intent=xxxxxxxxxxx` which shows a *Payment succeeded* message (see screenshot below).
7. In the console I see the following error: 
> Error when fetching PaymentIntent SyntaxError: Unexpected token < in JSON at position 2785
8. In the XHR I see that the JSON is actually there, but the response output also includes the HTML of the PHP notices (see screenshot below).

## Expected behavior

Step 6 should show the JSON output of the payment but got a couple of these notices in the XHR response:

> Notice: Trying to access array offset on value of type int in /Users/ronald/Sites/stripe.test/web-elements-ideal-payment/server/vendor/stripe/stripe-php/lib/Util/Util.php on line 45

## Temp fix
I can lower the PGHP `error_reporting` to not show notices and only errors.

## Screenshots

<img width="418" alt="Screenshot 2021-04-06 at 11 23 44" src="https://user-images.githubusercontent.com/7911547/113689356-8ee71080-96ca-11eb-9d24-4a3bcb78883d.png">

<img width="1783" alt="Screenshot 2021-04-06 at 11 36 19" src="https://user-images.githubusercontent.com/7911547/113691005-50525580-96cc-11eb-8348-826595725b90.png">

## System information

- OS: MacOS
- Browser: Any, server side problem
- Server environment: PHP 7.4

## Additional
I also got an error on the `/create-payment-intend` request where this line was giving me troubles in `server/vendor/stripe/stripe-php/lib/ApiRequestor.php` line 402:
```
if (array_key_exists('request-id', $rheaders)) {
```
Which I temp 'fixed' by replacing it with:
```
if (isset($rheaders['request-id'])) {
```

**Comment by cjavilla-stripe** [comment]
Thanks for that added context, @ronaldtveen! 

We're actually going to archive this repository and are promoting this new repo which shows how to implement ideal in addition to several other payment method types: https://github.com/stripe-samples/accept-a-payment/tree/main/custom-payment-flow/
